version: '3.8'

services:
  backend:
    build: ./backend
    container_name: ai-social-backend
    ports:
      - "8000:8000"
    env_file:
      - backend/.env
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: ai-social-frontend
    ports:
      - "3000:3000"
    env_file:
      - frontend/.env
    depends_on:
      - backend

  db:
    image: postgres:13
    container_name: ai-social-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ai_social
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: